name: calendar_event
description: カレンダービュー表示パッケージ
version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  equatable: ^2.0.5
  collection: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

scripts:
  # formatする
  format: .fvm/flutter_sdk/bin/dart fix --apply
  # analyzeする
  analyze: fvm flutter analyze . --no-fatal-infos
  # cache削除
  clean: fvm flutter clean
  # test実行
  test: fvm flutter test
  # indexGeneratorを実行する
  indexGenerator: dart pub global run index_generator

# export文を自動生成してくれるパッケージ
# dart pub global run index_generatorで自動生成してくれる
# https://pub.dev/packages/index_generator
index_generator:
  # Define the paths of the folders in which to generate the index files
  indexes:
    - path: lib
  exclude:
    - "**/*.freezed.dart"
